### ISSUE TITLE
Android客户端在选择服务器配置时二维码不能扫描

### ISSUE THREAD

**Issue by andywang1011** [lomorage/lomo-android-apk-release#1]
Android客户端在选择服务器配置时二维码不能扫描
![image](https://user-images.githubusercontent.com/40266446/125748182-269c3196-eda8-4313-aa05-ba347865fdc9.png)
Android客户端在使用过程中经常闪退.

**Comment by aisnote** [comment]
Please update from google play store, also please send feedback via app which will collect logs also.

**Comment by aisnote** [comment]
可以去 https://docs.lomorage.com/docs/Installation/lomorage-client/installation-android/ 下载最新的
