### ISSUE TITLE
需要开发者吗？

### ISSUE THREAD

**Issue by GuoMinJ** [lomorage/lomo-android-apk-release#10]
本人10年软件开发经验。有意志愿帮忙开发与维护，电话13951317705。

**Comment by aisnote** [comment]
![image](https://user-images.githubusercontent.com/1201634/229262403-467fa350-57de-48a4-be0b-df525bb5ee9e.jpeg)

**Comment by aisnote** [comment]
➕上面wechat

**Comment by lomolomo2** [comment]
加微信先。
