### ISSUE TITLE
The app doesn't recognize local unsynced changes

### ISSUE THREAD

**Issue by intelligear** [lomorage/lomo-android-apk-release#2]
When first time run, after the app connected to the service, it doesn't recognize any local unsynced changes, it displayed: "your xxxx assets have already been backed up", when clicked Start Sync, it prompted: "No asset need to backup", but in fact none of the pictures haven been uploaded.

**Comment by aisnote** [comment]
Please send log via app-  settings- send feedback, it will collect logs include server logs

**Comment by aisnote** [comment]
please go to https://docs.lomorage.com/docs/Installation/lomorage-client/installation-android/ to download the latest version.
