### ISSUE TITLE
The app got stuck on the splash page when opened for the 2nd time

### ISSUE THREAD

**Issue by intelligear** [lomorage/lomo-android-apk-release#3]
The app seems has performance problem and tried to load thousands pictures all at once, it caused ANR when first time loading the preview page. After quit and opened again, it got stuck on the start Splash page.

**Comment by aisnote** [comment]
Could you please send log from android app?

**Comment by aisnote** [comment]
fixed in the latest release:
https://docs.lomorage.com/docs/Installation/lomorage-client/installation-android/
