### ISSUE TITLE
Uploaded photos lossed GPS tag from Xiaomi MIUI12

### ISSUE THREAD

**Issue by aisnote** [lomorage/lomo-android-apk-release#5]
Refer to manifest and exifinterface helper.

https://github.com/lomorage/lomo-android-apk-release/blob/master/src/main/AndroidManifest.xml
https://github.com/lomorage/lomo-android-apk-release/blob/master/src/main/AssetExifInfoHelper.kt#L149

**Comment by Nahasapeemapetilon** [comment]
generally the app cannot read gps data

![image](https://user-images.githubusercontent.com/16188935/162378582-433a4a02-2210-4c6c-8dea-79addcec85f5.png)

this is my logcat file:
[output (1).log](https://github.com/lomorage/lomo-android-apk-release/files/8449207/output.1.log)

**Comment by aisnote** [comment]
This is just to read the pics exif tag. Maybe it is caused by the permission not be set right.

**Comment by aisnote** [comment]
And this is the code to upload the file to Lomorage server.
https://github.com/lomorage/lomo-android-apk-release/blob/master/src/main/UploadAsset.kt#L66
It is read the file as binary.
Maybe XIAOMI has potential bug. Or XIAO MIUI hooked the file reading? and remove the GPS tag?

I will build out the new APK to you which will add the right permission as MIUI stated to access the location info to see the issue can be solved or not. Anyway, thanks for your feedback.

**Comment by Nahasapeemapetilon** [comment]
where can i find the apk to test?

**Comment by Nahasapeemapetilon** [comment]
> This is just to read the pics exif tag. Maybe it is caused by the permission not be set right.

on standard upload to unraid server all my images lose gps data

**Comment by aisnote** [comment]
> where can i find the apk to test?

sorry for the delay, will post here in couple of days. thx

**Comment by aisnote** [comment]
@Nahasapeemapetilon  could you try this APK?
https://github.com/lomorage/lomo-android-apk-release/releases/download/2022-04-20_10-05-24/com.lomoware.lomorage-v41.0.944.-release2022-04-20_10-05-24.apk

And let me know the results. thanks for your help.

**Comment by Nahasapeemapetilon** [comment]
first quick test looks good
both files have the same checksum 
and contain gps data 

afterwards i will try again with 
./lomoc import name pass /importFolder/
from the nas and then sync with the mobile phone. and hope that I don't have any more duplicate files.

**Comment by Nahasapeemapetilon** [comment]
![5983164347460991540](https://user-images.githubusercontent.com/16188935/164454737-999d980b-d6d5-4a2d-a7ad-a65fa81fffb5.jpg)

**Comment by aisnote** [comment]
thanks for your update. Let us know if any issues.
