### ISSUE TITLE
Android app 可完善的几个地方

### ISSUE THREAD

**Issue by Zerorigin** [lomorage/lomo-android-apk-release#6]
1. 提供一个选项以打开“总是使用外网地址”，方便哪些在内网实施了 NAT 回环或部署了内部 DNS 服务的使用者
(或者可以想办法优化下内外网自动检测的逻辑，现在的检测逻辑好像有点迟缓，导致连接体验一般)

2. 使用外网地址时，如果外网地址是`https`协议时，在“资源详细信息”页面，使用“复制远程图片地址”按钮复制的到远程地址会错误的以`http://https://`开头，希望抽空修复下此问题

**Comment by aisnote** [comment]
谢谢。会尽快完善

**Comment by aisnote** [comment]
@Zerorigin  试试这个： [https://github.com/lomorage/lomo-android-apk-release/releases/tag/2022-11-11_10-45-57](https://github.com/lomorage/lomo-android-apk-release/releases/tag/2022-11-11_10-45-57)
看看有没有满足你的要求。谢谢

**Comment by Zerorigin** [comment]
> 

1. 第一点的可以始终使用外网地址了，连接体验确实上来了，但是出现了个新 bug，无法去掉勾选“用外网地址”，导致无法切换回内网 IP 登录的方式。
2. 第二点内外网登录复制的远程图片地址都正常了。赞噢

**Comment by aisnote** [comment]
第一点可能是因为你一开始就配置了远程。所以去掉☑️，也是读的上次你登录过的（远程）地址信息。

**Comment by aisnote** [comment]
你再试试看 ，或者贴个图上来

**Comment by Zerorigin** [comment]
> 第一点可能是因为你一开始就配置了远程。所以去掉☑️，也是读的上次你登录过的（远程）地址信息。

不是，是那个☑️点不掉

**Comment by aisnote** [comment]
我看看

**Comment by aisnote** [comment]
我的華爲手機，可以checked 和 unchecked 啊。发个video 到  微信或者 via gmail
